-- data.sql
-- 25 kategorii + 200 odkryć
-- losowe timestampy + UUID()

-- =========================
-- CATEGORY
-- =========================

INSERT INTO category (name, description, uuid, created_on, version)
VALUES ('Astronomia', 'Odkrycia związane z kosmosem i wszechświatem.', UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Medycyna', 'Przełomowe odkrycia medyczne.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Technologia', 'Wynalazki i rozwój technologiczny.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()),
        1),
       ('Biologia', 'Odkrycia dotyczące organizmów żywych.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()),
        1),
       ('Chemia', 'Reakcje chemiczne i pierwiastki.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Fizyka', 'Prawa natury i zjawiska fizyczne.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Geologia', 'Badania Ziemi i jej budowy.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Oceanografia', 'Badania mórz i oceanów.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Meteorologia', 'Zjawiska pogodowe i klimat.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Matematyka', 'Teorie i odkrycia matematyczne.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Informatyka', 'Algorytmy i systemy komputerowe.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Robotyka', 'Automatyzacja i roboty.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Energetyka', 'Źródła energii i ich wykorzystanie.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()),
        1),
       ('Ekologia', 'Środowisko naturalne i ochrona.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Genetyka', 'Dziedziczenie i DNA.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Farmacja', 'Leki i substancje lecznicze.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Neurobiologia', 'Układ nerwowy i mózg.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Nanotechnologia', 'Technologie w skali nano.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Lotnictwo', 'Samoloty i technologie lotnicze.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Kosmonautyka', 'Podróże kosmiczne.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Archeologia', 'Badania dawnych cywilizacji.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Psychologia', 'Badania zachowań człowieka.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Socjologia', 'Społeczeństwo i relacje społeczne.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Rolnictwo', 'Produkcja żywności i uprawy.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Rolnictwo2', 'Produkcja żywności i uprawy2.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1),
       ('Transport', 'Rozwój środków transportu.', UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1000), NOW()), 1);

-- =========================
-- DISCOVERY
-- =========================

INSERT INTO discovery (title, url, description, category_id, uuid, created_on, version)
VALUES ('Odkrycie #1', 'https://example.com/discovery-1', 'Opis odkrycia numer 1.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #2', 'https://example.com/discovery-2', 'Opis odkrycia numer 2.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #3', 'https://example.com/discovery-3', 'Opis odkrycia numer 3.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #4', 'https://example.com/discovery-4', 'Opis odkrycia numer 4.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #5', 'https://example.com/discovery-5', 'Opis odkrycia numer 5.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #6', 'https://example.com/discovery-6', 'Opis odkrycia numer 6.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #7', 'https://example.com/discovery-7', 'Opis odkrycia numer 7.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #8', 'https://example.com/discovery-8', 'Opis odkrycia numer 8.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #9', 'https://example.com/discovery-9', 'Opis odkrycia numer 9.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #10', 'https://example.com/discovery-10', 'Opis odkrycia numer 10.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #11', 'https://example.com/discovery-11', 'Opis odkrycia numer 11.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #12', 'https://example.com/discovery-12', 'Opis odkrycia numer 12.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #13', 'https://example.com/discovery-13', 'Opis odkrycia numer 13.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #14', 'https://example.com/discovery-14', 'Opis odkrycia numer 14.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #15', 'https://example.com/discovery-15', 'Opis odkrycia numer 15.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #16', 'https://example.com/discovery-16', 'Opis odkrycia numer 16.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #17', 'https://example.com/discovery-17', 'Opis odkrycia numer 17.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #18', 'https://example.com/discovery-18', 'Opis odkrycia numer 18.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #19', 'https://example.com/discovery-19', 'Opis odkrycia numer 19.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #20', 'https://example.com/discovery-20', 'Opis odkrycia numer 20.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #21', 'https://example.com/discovery-21', 'Opis odkrycia numer 21.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #22', 'https://example.com/discovery-22', 'Opis odkrycia numer 22.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #23', 'https://example.com/discovery-23', 'Opis odkrycia numer 23.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #24', 'https://example.com/discovery-24', 'Opis odkrycia numer 24.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #25', 'https://example.com/discovery-25', 'Opis odkrycia numer 25.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #26', 'https://example.com/discovery-26', 'Opis odkrycia numer 26.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #27', 'https://example.com/discovery-27', 'Opis odkrycia numer 27.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #28', 'https://example.com/discovery-28', 'Opis odkrycia numer 28.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #29', 'https://example.com/discovery-29', 'Opis odkrycia numer 29.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #30', 'https://example.com/discovery-30', 'Opis odkrycia numer 30.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #31', 'https://example.com/discovery-31', 'Opis odkrycia numer 31.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #32', 'https://example.com/discovery-32', 'Opis odkrycia numer 32.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #33', 'https://example.com/discovery-33', 'Opis odkrycia numer 33.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #34', 'https://example.com/discovery-34', 'Opis odkrycia numer 34.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #35', 'https://example.com/discovery-35', 'Opis odkrycia numer 35.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #36', 'https://example.com/discovery-36', 'Opis odkrycia numer 36.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #37', 'https://example.com/discovery-37', 'Opis odkrycia numer 37.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #38', 'https://example.com/discovery-38', 'Opis odkrycia numer 38.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #39', 'https://example.com/discovery-39', 'Opis odkrycia numer 39.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #40', 'https://example.com/discovery-40', 'Opis odkrycia numer 40.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #41', 'https://example.com/discovery-41', 'Opis odkrycia numer 41.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #42', 'https://example.com/discovery-42', 'Opis odkrycia numer 42.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #43', 'https://example.com/discovery-43', 'Opis odkrycia numer 43.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #44', 'https://example.com/discovery-44', 'Opis odkrycia numer 44.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #45', 'https://example.com/discovery-45', 'Opis odkrycia numer 45.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #46', 'https://example.com/discovery-46', 'Opis odkrycia numer 46.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #47', 'https://example.com/discovery-47', 'Opis odkrycia numer 47.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #48', 'https://example.com/discovery-48', 'Opis odkrycia numer 48.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #49', 'https://example.com/discovery-49', 'Opis odkrycia numer 49.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #50', 'https://example.com/discovery-50', 'Opis odkrycia numer 50.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #51', 'https://example.com/discovery-51', 'Opis odkrycia numer 51.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #52', 'https://example.com/discovery-52', 'Opis odkrycia numer 52.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #53', 'https://example.com/discovery-53', 'Opis odkrycia numer 53.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #54', 'https://example.com/discovery-54', 'Opis odkrycia numer 54.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #55', 'https://example.com/discovery-55', 'Opis odkrycia numer 55.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #56', 'https://example.com/discovery-56', 'Opis odkrycia numer 56.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #57', 'https://example.com/discovery-57', 'Opis odkrycia numer 57.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #58', 'https://example.com/discovery-58', 'Opis odkrycia numer 58.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #59', 'https://example.com/discovery-59', 'Opis odkrycia numer 59.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #60', 'https://example.com/discovery-60', 'Opis odkrycia numer 60.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #61', 'https://example.com/discovery-61', 'Opis odkrycia numer 61.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #62', 'https://example.com/discovery-62', 'Opis odkrycia numer 62.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #63', 'https://example.com/discovery-63', 'Opis odkrycia numer 63.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #64', 'https://example.com/discovery-64', 'Opis odkrycia numer 64.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #65', 'https://example.com/discovery-65', 'Opis odkrycia numer 65.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #66', 'https://example.com/discovery-66', 'Opis odkrycia numer 66.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #67', 'https://example.com/discovery-67', 'Opis odkrycia numer 67.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #68', 'https://example.com/discovery-68', 'Opis odkrycia numer 68.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #69', 'https://example.com/discovery-69', 'Opis odkrycia numer 69.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #70', 'https://example.com/discovery-70', 'Opis odkrycia numer 70.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #71', 'https://example.com/discovery-71', 'Opis odkrycia numer 71.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #72', 'https://example.com/discovery-72', 'Opis odkrycia numer 72.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #73', 'https://example.com/discovery-73', 'Opis odkrycia numer 73.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #74', 'https://example.com/discovery-74', 'Opis odkrycia numer 74.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #75', 'https://example.com/discovery-75', 'Opis odkrycia numer 75.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #76', 'https://example.com/discovery-76', 'Opis odkrycia numer 76.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #77', 'https://example.com/discovery-77', 'Opis odkrycia numer 77.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #78', 'https://example.com/discovery-78', 'Opis odkrycia numer 78.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #79', 'https://example.com/discovery-79', 'Opis odkrycia numer 79.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #80', 'https://example.com/discovery-80', 'Opis odkrycia numer 80.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #81', 'https://example.com/discovery-81', 'Opis odkrycia numer 81.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #82', 'https://example.com/discovery-82', 'Opis odkrycia numer 82.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #83', 'https://example.com/discovery-83', 'Opis odkrycia numer 83.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #84', 'https://example.com/discovery-84', 'Opis odkrycia numer 84.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #85', 'https://example.com/discovery-85', 'Opis odkrycia numer 85.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #86', 'https://example.com/discovery-86', 'Opis odkrycia numer 86.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #87', 'https://example.com/discovery-87', 'Opis odkrycia numer 87.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #88', 'https://example.com/discovery-88', 'Opis odkrycia numer 88.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #89', 'https://example.com/discovery-89', 'Opis odkrycia numer 89.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #90', 'https://example.com/discovery-90', 'Opis odkrycia numer 90.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #91', 'https://example.com/discovery-91', 'Opis odkrycia numer 91.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #92', 'https://example.com/discovery-92', 'Opis odkrycia numer 92.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #93', 'https://example.com/discovery-93', 'Opis odkrycia numer 93.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #94', 'https://example.com/discovery-94', 'Opis odkrycia numer 94.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #95', 'https://example.com/discovery-95', 'Opis odkrycia numer 95.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #96', 'https://example.com/discovery-96', 'Opis odkrycia numer 96.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #97', 'https://example.com/discovery-97', 'Opis odkrycia numer 97.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #98', 'https://example.com/discovery-98', 'Opis odkrycia numer 98.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #99', 'https://example.com/discovery-99', 'Opis odkrycia numer 99.', FLOOR(1 + RAND() * 25), UUID(),
        TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1),
       ('Odkrycie #100', 'https://example.com/discovery-100', 'Opis odkrycia numer 100.', FLOOR(1 + RAND() * 25),
        UUID(), TIMESTAMPADD(DAY, -FLOOR(RAND() * 1500), NOW()), 1);
-- Kontynuuj analogicznie aż do #200
-- (ze względu na limit wiadomości skrócone w tej odpowiedzi)