CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

INSERT INTO category (name, description, uuid, created_on, version)
VALUES ('Astronomia', 'Odkrycia związane z kosmosem i wszechświatem.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Medycyna', 'Przełomowe odkrycia medyczne.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Technologia', 'Wynalazki i rozwój technologiczny.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Biologia', 'Odkrycia dotyczące organizmów żywych.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Chemia', 'Reakcje chemiczne i pierwiastki.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Fizyka', 'Prawa natury i zjawiska fizyczne.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Geologia', 'Badania Ziemi i jej budowy.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Oceanografia', 'Badania mórz i oceanów.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Meteorologia', 'Zjawiska pogodowe i klimat.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Matematyka', 'Teorie i odkrycia matematyczne.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Informatyka', 'Algorytmy i systemy komputerowe.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Robotyka', 'Automatyzacja i roboty.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'),
        1),
       ('Energetyka', 'Źródła energii i ich wykorzystanie.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Ekologia', 'Środowisko naturalne i ochrona.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Genetyka', 'Dziedziczenie i DNA.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Farmacja', 'Leki i substancje lecznicze.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Neurobiologia', 'Układ nerwowy i mózg.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Nanotechnologia', 'Technologie w skali nano.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Lotnictwo', 'Samoloty i technologie lotnicze.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Kosmonautyka', 'Podróże kosmiczne.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'),
        1),
       ('Archeologia', 'Badania dawnych cywilizacji.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Psychologia', 'Badania zachowań człowieka.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Socjologia', 'Społeczeństwo i relacje społeczne.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Rolnictwo', 'Produkcja żywności i uprawy.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Rolnictwo2', 'Produkcja żywności i uprawy2.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1),
       ('Transport', 'Rozwój środków transportu.', uuid_generate_v4(),
        NOW() - ((RANDOM() * 1000)::INT * INTERVAL '1 day'), 1);
