CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

INSERT INTO discovery (title, url, description, category_id, uuid, created_on, version)
VALUES ('Odkrycie #1', 'https://example.com/discovery-1', 'Opis odkrycia numer 1', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #2', 'https://example.com/discovery-2', 'Opis odkrycia numer 2', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #3', 'https://example.com/discovery-3', 'Opis odkrycia numer 3', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #4', 'https://example.com/discovery-4', 'Opis odkrycia numer 4', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #5', 'https://example.com/discovery-5', 'Opis odkrycia numer 5', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #6', 'https://example.com/discovery-6', 'Opis odkrycia numer 6', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #7', 'https://example.com/discovery-7', 'Opis odkrycia numer 7', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #8', 'https://example.com/discovery-8', 'Opis odkrycia numer 8', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #9', 'https://example.com/discovery-9', 'Opis odkrycia numer 9', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #10', 'https://example.com/discovery-10', 'Opis odkrycia numer 10', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #11', 'https://example.com/discovery-11', 'Opis odkrycia numer 11', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #12', 'https://example.com/discovery-12', 'Opis odkrycia numer 12', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #13', 'https://example.com/discovery-13', 'Opis odkrycia numer 13', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #14', 'https://example.com/discovery-14', 'Opis odkrycia numer 14', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #15', 'https://example.com/discovery-15', 'Opis odkrycia numer 15', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #16', 'https://example.com/discovery-16', 'Opis odkrycia numer 16', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #17', 'https://example.com/discovery-17', 'Opis odkrycia numer 17', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #18', 'https://example.com/discovery-18', 'Opis odkrycia numer 18', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #19', 'https://example.com/discovery-19', 'Opis odkrycia numer 19', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #20', 'https://example.com/discovery-20', 'Opis odkrycia numer 20', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #21', 'https://example.com/discovery-21', 'Opis odkrycia numer 21', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #22', 'https://example.com/discovery-22', 'Opis odkrycia numer 22', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #23', 'https://example.com/discovery-23', 'Opis odkrycia numer 23', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #24', 'https://example.com/discovery-24', 'Opis odkrycia numer 24', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #25', 'https://example.com/discovery-25', 'Opis odkrycia numer 25', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #26', 'https://example.com/discovery-26', 'Opis odkrycia numer 26', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #27', 'https://example.com/discovery-27', 'Opis odkrycia numer 27', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #28', 'https://example.com/discovery-28', 'Opis odkrycia numer 28', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #29', 'https://example.com/discovery-29', 'Opis odkrycia numer 29', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #30', 'https://example.com/discovery-30', 'Opis odkrycia numer 30', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),

       ('Odkrycie #31', 'https://example.com/discovery-31', 'Opis odkrycia numer 31', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #32', 'https://example.com/discovery-32', 'Opis odkrycia numer 32', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #33', 'https://example.com/discovery-33', 'Opis odkrycia numer 33', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #34', 'https://example.com/discovery-34', 'Opis odkrycia numer 34', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #35', 'https://example.com/discovery-35', 'Opis odkrycia numer 35', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #36', 'https://example.com/discovery-36', 'Opis odkrycia numer 36', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #37', 'https://example.com/discovery-37', 'Opis odkrycia numer 37', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #38', 'https://example.com/discovery-38', 'Opis odkrycia numer 38', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #39', 'https://example.com/discovery-39', 'Opis odkrycia numer 39', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1),
       ('Odkrycie #40', 'https://example.com/discovery-40', 'Opis odkrycia numer 40', (1 + (RANDOM() * 25)::INT),
        uuid_generate_v4(), NOW() - ((RANDOM() * 1500)::INT * INTERVAL '1 day'), 1)
